server {
    listen 80;
    server_name jfernando.dev www.jfernando.dev;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://portfolio:3000;
    }
}
